import type { FeatureFlagGroup } from './types';

export const FEATURE_FLAG_GROUPS: FeatureFlagGroup[] = [
  {
    id: 'legacy',
    label: 'Compatibilidade',
    description: 'Flags legadas mantidas para componentes antigos e receitas já existentes.',
    keys: [
      'ecom.header',
      'ecom.footer',
      'ecom.heroBanner',
      'ecom.servicesBar',
      'ecom.carousel',
      'ecom.showcaseDaily',
      'ecom.showcaseGrocery',
      'ecom.demoBanners',
      'ecom.demoShelves',
      'ecom.cart',
    ],
  },
  {
    id: 'layout',
    label: 'Layout',
    description: 'Controle estrutural do shell principal do e-commerce.',
    keys: ['ecom.layout.header', 'ecom.layout.footer', 'ecom.layout.drawerCart', 'ecom.siteResolver.enabled', 'ecom.siteResolver.overrideHome'],
  },
  {
    id: 'header',
    label: 'Header',
    description: 'Elementos do cabeçalho, busca, atalhos e navegação.',
    keys: [
      'ecom.header.promoBar',
      'ecom.header.deliveryPill',
      'ecom.header.utilBar',
      'ecom.header.util.club',
      'ecom.header.util.help',
      'ecom.header.util.login',
      'ecom.header.topRow',
      'ecom.header.logo',
      'ecom.header.search',
      'ecom.header.actions.favorite',
      'ecom.header.actions.cart',
      'ecom.header.actions.loginQuick',
      'ecom.header.actions.account',
      'ecom.header.nav',
      'ecom.header.nav.departments',
      'ecom.header.nav.meta',
      'ecom.header.condensed',
      'ecom.header.backToTop',
    ],
  },
  {
    id: 'home',
    label: 'Home',
    description: 'Blocos promocionais e vitrines da página inicial.',
    keys: [
      'ecom.home.hero.main',
      'ecom.home.showcase.daily',
      'ecom.home.services',
      'ecom.home.showcase.grocery',
      'ecom.home.banner.heroLarge',
      'ecom.home.banner.strip.1',
      'ecom.home.banner.strip.2',
      'ecom.home.banner.strip.3',
      'ecom.home.demo.carousel.twoItems',
      'ecom.home.demo.carousel.manyItems',
    ],
  },
  {
    id: 'plp',
    label: 'PLP',
    description: 'Listagem de produtos, filtros e paginação.',
    keys: ['ecom.plp.header', 'ecom.plp.toolbar', 'ecom.plp.facets', 'ecom.plp.grid', 'ecom.plp.pagination', 'ecom.plp.emptyState', 'ecom.plp.loadingSkeleton'],
  },
  {
    id: 'pdp',
    label: 'PDP',
    description: 'Componentes da página de produto.',
    keys: ['ecom.pdp.breadcrumbs', 'ecom.pdp.gallery', 'ecom.pdp.priceActions', 'ecom.pdp.primeBadge', 'ecom.pdp.about', 'ecom.pdp.tabs', 'ecom.pdp.extraPanels', 'ecom.pdp.related'],
  },
  {
    id: 'cart',
    label: 'Carrinho e Drawer',
    description: 'Controles do carrinho de página e do drawer lateral.',
    keys: [
      'ecom.cartPage.title',
      'ecom.cartPage.items',
      'ecom.cartPage.summary',
      'ecom.cartPage.empty',
      'ecom.drawer.promotionBanner',
      'ecom.drawer.viewSwitch',
      'ecom.drawer.list.compact',
      'ecom.drawer.list.detailed',
      'ecom.drawer.footerSummary',
    ],
  },
  {
    id: 'checkout',
    label: 'Checkout',
    description: 'Etapas e blocos de apoio do checkout.',
    keys: [
      'ecom.checkout.error',
      'ecom.checkout.step.profile',
      'ecom.checkout.step.address',
      'ecom.checkout.step.shipping',
      'ecom.checkout.step.payment',
      'ecom.checkout.step.review',
      'ecom.checkout.asideSummary',
    ],
  },
  {
    id: 'account',
    label: 'Minha conta',
    description: 'Experiência da conta do cliente.',
    keys: ['ecom.account', 'ecom.account.orders', 'ecom.account.profile', 'ecom.account.addresses'],
  },
];
